name: Deploy Web Application

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - name: build production app
        uses: actions/checkout@v2
      - run: npm i
      - run: npm run build
      - run: |
          ls
      - uses: actions/checkout@v2
      - name: Install surge and fire deployment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g surge
      - run: surge dist redis-web-client-preview-${{github.event.pull_request.number}}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
