name: Deploy Preview Web

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and trigger deployment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g surge pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: surge ./dist redis-web-client-preview-${{github.event.pull_request.number}}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
