name: release_app

on: create

jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and trigger deployment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g surge
      - run: npm i
      - run: npm run build
      - run: surge ./dist redis-web-client.surge.sh --token ${{ secrets.SURGE_TOKEN }}
